(function(){
const {trees,defs,feelings,subtexts}=window.GAME_DATA;
const $=id=>document.getElementById(id);
const screens={home:$("home-screen"),game:$("game-screen"),orchard:$("orchard-screen")};
const STORE_KEY="eq-superman-mvp-v1";
const ANALYTICS_KEY="eq-superman-analytics-v1";
const IMAGE_PRIORITY_KEY="eq-superman-image-priority";
const CREATOR_MODE_KEY="eq-superman-creator-mode";
const MAX_ANALYTICS_EVENTS=1200;
const makeAnonymousId=()=>crypto.randomUUID?crypto.randomUUID():`anon-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const emptyProgress=()=>({schemaVersion:2,anonymousId:makeAnonymousId(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastSyncedAt:null,rounds:0,attempts:0,concepts:{},history:[]});
let progress=loadProgress();
const sessionId=makeAnonymousId();
let analytics=loadAnalytics();
let state={mode:null,deck:[],index:0,seconds:20,timer:null,autoTimer:null,textTimers:[],locked:false,correct:0,streak:0,bestStreak:0,creatorMode:false,roundId:null,questionStartedAt:null,sessionConcepts:new Set(),newConcepts:new Set(),grownConcepts:new Set()};

function loadProgress(){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY)||"{}");const migrated={...emptyProgress(),...saved,schemaVersion:2,anonymousId:saved.anonymousId||makeAnonymousId(),history:Array.isArray(saved.history)?saved.history:[],concepts:saved.concepts||{}};localStorage.setItem(STORE_KEY,JSON.stringify(migrated));return migrated}catch{return emptyProgress()}}
function saveProgress(){progress.updatedAt=new Date().toISOString();localStorage.setItem(STORE_KEY,JSON.stringify(progress))}
function getEnvironment(){const path=location.pathname;return path.includes("emotion-catcher-staging")?"staging":"production"}
function loadAnalytics(){try{const saved=JSON.parse(localStorage.getItem(ANALYTICS_KEY)||"{}");return{schemaVersion:1,anonymousId:progress.anonymousId,createdAt:saved.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),lastUploadedAt:saved.lastUploadedAt||null,events:Array.isArray(saved.events)?saved.events.slice(-MAX_ANALYTICS_EVENTS):[]}}catch{return{schemaVersion:1,anonymousId:progress.anonymousId,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),lastUploadedAt:null,events:[]}}}
function saveAnalytics(){analytics.anonymousId=progress.anonymousId;analytics.updatedAt=new Date().toISOString();analytics.events=analytics.events.slice(-MAX_ANALYTICS_EVENTS);localStorage.setItem(ANALYTICS_KEY,JSON.stringify(analytics))}
function track(event,props={}){try{analytics.events.push({id:makeAnonymousId(),event,props,anonymousId:progress.anonymousId,sessionId,environment:getEnvironment(),path:location.pathname,createdAt:new Date().toISOString()});saveAnalytics()}catch{}}
window.EQSupermanStorage={exportForAccount(){return JSON.parse(JSON.stringify({source:"browser-local",storageKey:STORE_KEY,exportedAt:new Date().toISOString(),payload:progress,analytics:analytics.events}))},markSynced(){progress.lastSyncedAt=new Date().toISOString();saveProgress()},schemaVersion:2};
window.EQSupermanAnalytics={export(){return JSON.parse(JSON.stringify({source:"browser-local",storageKey:ANALYTICS_KEY,exportedAt:new Date().toISOString(),payload:analytics}))},markUploaded(){analytics.lastUploadedAt=new Date().toISOString();saveAnalytics()},clear(){analytics={...analytics,updatedAt:new Date().toISOString(),events:[]};saveAnalytics()},track,count(){return analytics.events.length},schemaVersion:1};
let audioContext=null;
function playSound(type){try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)();const patterns={success:[[523,.08],[659,.08],[784,.16]],fail:[[247,.12],[196,.2]],finish:[[523,.09],[659,.09],[784,.09],[1047,.28]],fruitNew:[[659,.07],[880,.1],[1175,.2]],fruitGrow:[[392,.08],[523,.09],[659,.22]]};let at=audioContext.currentTime+.01;(patterns[type]||[]).forEach(([frequency,duration])=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=type==="fail"?"triangle":"sine";oscillator.frequency.setValueAtTime(frequency,at);gain.gain.setValueAtTime(.0001,at);gain.gain.exponentialRampToValueAtTime(type==="fail"?.09:.12,at+.015);gain.gain.exponentialRampToValueAtTime(.0001,at+duration);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(at);oscillator.stop(at+duration+.02);at+=duration*.78})}catch{}}
function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
function showScreen(name){Object.entries(screens).forEach(([key,el])=>el.classList.toggle("is-hidden",key!==name));window.scrollTo(0,0);track("screen_view",{screen:name})}
function normalize(text){return text.trim().toLowerCase().replace(/[，。！？、,.!?“”"'\s]/g,"").replace(/我觉得|我感到|感觉是|应该是|有一点|有点|非常/g,"")}
function conceptRecord(name){return progress.concepts[name]||{seen:0,correct:0,questionIds:[],modes:[],lastSeen:null}}
function masteryStage(record){if(Number.isInteger(record.growthStage))return Math.max(0,Math.min(3,record.growthStage));if(!record.seen)return 0;if(!record.correct)return 1;if(record.correct<3||record.questionIds.length<2)return 2;return 3}
function allConceptNames(){return trees.flatMap(tree=>tree.concepts)}
function stats(){const records=allConceptNames().map(conceptRecord);return{discovered:records.filter(r=>r.seen).length,ripe:records.filter(r=>masteryStage(r)===3).length,total:records.length}}
function updateHome(){const s=stats();$("home-fruit-count").textContent=s.discovered;$("stat-discovered").textContent=s.discovered;$("stat-ripe").textContent=s.ripe;$("stat-rounds").textContent=progress.rounds}
function imagePriorityEnabled(){return $("image-priority-toggle")?.checked}
function creatorModeEnabled(){return $("creator-mode-toggle")?.checked}
function buildDeck(source){if(!imagePriorityEnabled())return shuffle(source).slice(0,8);const illustrated=shuffle(source.filter(q=>q.image)),plain=shuffle(source.filter(q=>!q.image));return[...illustrated,...plain].slice(0,8)}
function clearTextTimers(){(state.textTimers||[]).forEach(clearTimeout);state.textTimers=[]}
function scheduleTextTimer(fn,delay){const id=setTimeout(()=>{state.textTimers=(state.textTimers||[]).filter(timer=>timer!==id);fn()},delay);state.textTimers=[...(state.textTimers||[]),id];return id}
function typeText(el,text,duration,onDone){el.textContent="";const chars=[...String(text||"")];if(!chars.length){onDone?.();return}const interval=Math.max(18,duration/chars.length);chars.forEach((char,index)=>scheduleTextTimer(()=>{el.textContent+=char;if(index===chars.length-1)onDone?.()},Math.round(interval*(index+1))))}
function showFullQuestionText(q){clearTextTimers();$("scene-text").textContent=q.scene;$("question-prompt").textContent=q.prompt;$("question-prompt").classList.add("is-stamped")}
function startQuestionCountdown(){clearInterval(state.timer);updateTimer();state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0){state.creatorMode?revealCreatorAnswer():resolveAnswer("",true)}},1000)}
function animateQuestionText(q){typeText($("scene-text"),q.scene,4000,()=>typeText($("question-prompt"),q.prompt,800,()=>{$("question-prompt").classList.add("is-stamped");startQuestionCountdown()}))}
function startCreatorAutoAdvance(){let seconds=5;const last=state.index===state.deck.length-1,next=$("next-question");next.textContent=last?`回到首页（${seconds}）`:`下一题（${seconds}）`;clearInterval(state.autoTimer);state.autoTimer=setInterval(()=>{seconds--;next.textContent=last?`回到首页（${seconds}）`:`下一题（${seconds}）`;if(seconds<=0)advance()},1000)}

function startGame(mode){clearTimers();const source=mode==="feeling"?feelings:subtexts;state={mode,deck:buildDeck(source),index:0,seconds:20,timer:null,autoTimer:null,textTimers:[],locked:false,correct:0,streak:0,bestStreak:0,creatorMode:creatorModeEnabled(),roundId:makeAnonymousId(),questionStartedAt:null,sessionConcepts:new Set(),newConcepts:new Set(),grownConcepts:new Set()};track("round_start",{roundId:state.roundId,mode,total:state.deck.length,questionIds:state.deck.map(q=>q.id),imagePriority:imagePriorityEnabled(),creatorMode:state.creatorMode});const feeling=mode==="feeling";$("game-mode-index").textContent=feeling?"01":"02";$("game-mode-name").textContent=feeling?"识别感受":"弦外之音";$("game-mode-goal").textContent=state.creatorMode?"倒计时后揭晓答案":feeling?"为这一刻找到名字":"听见没有说出口的需要";showScreen("game");renderQuestion()}
function renderQuestion(){clearTextTimers();const q=state.deck[state.index],hasImage=Boolean(q.image),visual=$("question-visual"),image=$("question-image"),prompt=$("question-prompt");state.seconds=20;state.locked=false;state.questionStartedAt=Date.now();track("question_shown",{roundId:state.roundId,mode:state.mode,index:state.index+1,total:state.deck.length,questionId:q.id,concept:q.concept,target:q.target,hasImage,creatorMode:state.creatorMode});$("question-current").textContent=state.index+1;$("question-total").textContent=state.deck.length;$("progress-bar").style.width=`${(state.index+1)/state.deck.length*100}%`;$("context-label").textContent=q.context;$("scene-text").textContent="";prompt.textContent="";prompt.classList.remove("is-stamped");$("npc-status").textContent=state.creatorMode?"倒计时结束后揭晓答案":state.mode==="feeling"?"想请你听一件事":"这句话好像没有说完";$("answer-label").textContent=state.creatorMode?"先在心里想一个词":state.mode==="feeling"?"用一个感受词回答":"用一个词或一句短话回答";$("answer-input").placeholder=state.creatorMode?"":state.mode==="feeling"?"例如：委屈":"例如：希望被重视";$("answer-input").maxlength=state.mode==="feeling"?12:40;$("answer-input").value="";$("answer-input").disabled=state.creatorMode;$("submit-answer").disabled=state.creatorMode;$("submit-answer").textContent="判断";$("answer-hint").textContent=state.creatorMode?"答案出现前，先给这一刻取一个名字。":state.mode==="feeling"?"越准确的词，越能接近这一刻。":"不用猜台词，试着说出背后的感受或需要。";$("question-stage").classList.toggle("has-image",hasImage);$("game-screen").classList.toggle("creator-mode",state.creatorMode);visual.classList.toggle("has-image",hasImage);visual.classList.toggle("no-image",!hasImage);visual.classList.toggle("image-hidden",!hasImage);visual.classList.toggle("image-blurred",hasImage);visual.classList.remove("image-revealed");if(hasImage){image.src=q.image;image.alt=`${q.context} 插图`}else{image.removeAttribute("src");image.alt=""}$("feedback-layer").classList.toggle("image-feedback",hasImage);updateTimer();clearInterval(state.timer);animateQuestionText(q);if(!state.creatorMode)setTimeout(()=>$("answer-input").focus(),80)}
function updateTimer(){$("timer").textContent=state.seconds;$("timer").classList.toggle("urgent",state.seconds<=5)}
function grade(q,raw,timedOut){if(timedOut||!normalize(raw))return"timeout";const answer=normalize(raw);if(q.accepted.some(word=>answer.includes(normalize(word))))return"correct";if((q.near||[]).some(word=>answer.includes(normalize(word))))return"near";return"wrong"}
function recordAttempt(q,passed){const before=conceptRecord(q.concept),beforeStage=masteryStage(before);const record={...before,seen:before.seen+1,correct:before.correct+(passed?1:0),questionIds:[...new Set([...before.questionIds,q.id])],modes:[...new Set([...before.modes,q.mode])],lastSeen:new Date().toISOString()};let afterStage=beforeStage;if(beforeStage===0)afterStage=1;else if(passed&&beforeStage===1)afterStage=2;else if(passed&&beforeStage===2&&record.correct>=3&&record.questionIds.length>=2)afterStage=3;record.growthStage=afterStage;progress.concepts[q.concept]=record;progress.attempts++;saveProgress();state.sessionConcepts.add(q.concept);if(beforeStage===0)state.newConcepts.add(q.concept);if(afterStage>beforeStage&&beforeStage>0)state.grownConcepts.add(q.concept);track("concept_progress",{roundId:state.roundId,questionId:q.id,concept:q.concept,passed,beforeStage,afterStage,seen:record.seen,correct:record.correct})}
function revealCreatorAnswer(){if(state.locked)return;state.locked=true;clearInterval(state.timer);const q=state.deck[state.index],responseMs=state.questionStartedAt?Date.now()-state.questionStartedAt:null;showFullQuestionText(q);track("creator_answer_revealed",{roundId:state.roundId,mode:state.mode,index:state.index+1,questionId:q.id,concept:q.concept,target:q.target,responseMs});$("answer-input").disabled=true;$("submit-answer").disabled=true;if(q.image){$("question-visual").classList.remove("image-blurred");$("question-visual").classList.add("image-revealed")}playSound("success");const card=$("feedback-card");card.classList.remove("fail");$("feedback-icon").textContent="答";$("feedback-kicker").textContent="答案揭晓";$("feedback-target").textContent=`正确答案：${q.target}`;$("feedback-reference").textContent=state.mode==="subtext"?`参考表达：${q.reference}`:`关键词：${q.target}`;$("feedback-explanation").textContent=q.explanation;$("feedback-score").textContent="记住这个词，下次遇见类似瞬间会更快认出来。";$("next-question").textContent=state.index===state.deck.length-1?"回到首页 →":"下一题 →";$("feedback-layer").classList.remove("is-hidden");track("feedback_shown",{roundId:state.roundId,questionId:q.id,verdict:"creator_reveal",passed:null,target:q.target});setTimeout(()=>$("next-question").focus(),40);startCreatorAutoAdvance()}
function resolveAnswer(raw,timedOut=false){if(state.locked)return;if(state.creatorMode){revealCreatorAnswer();return}state.locked=true;clearInterval(state.timer);const q=state.deck[state.index],responseMs=state.questionStartedAt?Date.now()-state.questionStartedAt:null,verdict=grade(q,raw,timedOut),passed=verdict==="correct";showFullQuestionText(q);track("answer_submitted",{roundId:state.roundId,mode:state.mode,index:state.index+1,questionId:q.id,concept:q.concept,target:q.target,verdict,passed,timedOut,responseMs,answer:String(raw||"").trim().slice(0,80)});recordAttempt(q,passed);$("answer-input").disabled=true;$("submit-answer").disabled=true;if(q.image){$("question-visual").classList.remove("image-blurred");$("question-visual").classList.add("image-revealed")}if(passed){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak)}else state.streak=0;playSound(passed?"success":"fail");const card=$("feedback-card");card.classList.toggle("fail",!passed);$("feedback-icon").textContent=passed?"✓":"×";$("feedback-kicker").textContent=passed?"你听准了":verdict==="near"?"很接近，再准一点":verdict==="timeout"?"时间到了":"这一次没有命中";$("feedback-target").textContent=`${passed?"准确答案":"更贴近的是"}：${q.target}`;$("feedback-reference").textContent=state.mode==="subtext"?`参考表达：${q.reference}`:`关键词：${q.target}`;$("feedback-explanation").textContent=q.explanation;$("feedback-score").textContent=passed?`+1 果实经验 · ${state.streak} 连续答对`:`「${q.concept}」已收进果园，等待下次长大`;$("next-question").textContent=state.index===state.deck.length-1?"查看果园 →":"下一题 →";$("feedback-layer").classList.remove("is-hidden");track("feedback_shown",{roundId:state.roundId,questionId:q.id,verdict,passed,target:q.target});setTimeout(()=>$("next-question").focus(),40)}
function advance(){if($("feedback-layer").classList.contains("is-hidden"))return;track("feedback_advanced",{roundId:state.roundId,index:state.index+1,isLast:state.index===state.deck.length-1});clearInterval(state.autoTimer);$("feedback-layer").classList.add("is-hidden");state.index++;if(state.index>=state.deck.length)finishRound();else renderQuestion()}
function finishRound(){clearTimers();if(state.creatorMode){track("round_finish",{roundId:state.roundId,mode:state.mode,creatorMode:true,total:state.deck.length});$("settlement-layer").classList.add("is-hidden");updateHome();showScreen("home");return}progress.rounds++;progress.history=progress.history||[];progress.history.unshift({id:Date.now(),mode:state.mode,correct:state.correct,total:state.deck.length,bestStreak:state.bestStreak,newCount:state.newConcepts.size,concepts:[...state.sessionConcepts]});progress.history=progress.history.slice(0,20);saveProgress();track("round_finish",{roundId:state.roundId,mode:state.mode,correct:state.correct,total:state.deck.length,bestStreak:state.bestStreak,newConcepts:[...state.newConcepts],grownConcepts:[...state.grownConcepts],concepts:[...state.sessionConcepts]});renderOrchard();renderHistory();showScreen("orchard");$("settle-correct").textContent=`${state.correct}/${state.deck.length}`;$("settle-new").textContent=state.newConcepts.size;$("settle-grown").textContent=state.grownConcepts.size;$("settlement-title").textContent=state.correct>=6?"这一局，你听得很准":"果园记住了这次练习";$("settlement-copy").textContent=`完成「${state.mode==="feeling"?"识别感受":"弦外之音"}」，最长连续答对 ${state.bestStreak} 题。`;const names=[...new Set([...state.newConcepts,...state.grownConcepts])];$("settle-fruits").innerHTML=names.length?names.map(n=>{const label=state.newConcepts.has(n)&&state.grownConcepts.has(n)?"新认识并长大":state.newConcepts.has(n)?"新认识":"长大";return`<span>${label} · ${n}</span>`}).join(""):"<span>继续练习，果子会慢慢成熟</span>";$("settlement-layer").classList.remove("is-hidden");track("settlement_shown",{roundId:state.roundId,correct:state.correct,total:state.deck.length,newCount:state.newConcepts.size,grownCount:state.grownConcepts.size});playSound("finish");updateHome()}
function revealOrchardChanges(){track("settlement_closed",{roundId:state.roundId,action:"stay_orchard"});$("settlement-layer").classList.add("is-hidden");requestAnimationFrame(()=>{renderOrchard(true);if(state.newConcepts.size)setTimeout(()=>playSound("fruitNew"),100);if(state.grownConcepts.size)setTimeout(()=>playSound("fruitGrow"),state.newConcepts.size?500:100)})}
function clearTimers(){clearInterval(state.timer);clearInterval(state.autoTimer);clearTextTimers()}

const positions=[[14,23],[50,14],[86,23],[27,50],[73,50],[12,80],[50,80],[88,80]];
const labelPositions=["label-top","label-bottom","label-top","label-bottom","label-bottom","label-bottom","label-bottom","label-bottom"];
function renderOrchard(animate=false){const s=stats();$("orchard-summary").textContent=`${s.discovered} / ${s.total} 已点亮`;$("orchard-map").innerHTML=trees.map(tree=>{const lit=tree.concepts.filter(name=>conceptRecord(name).seen).length;const fruits=tree.concepts.map((name,i)=>{const stage=masteryStage(conceptRecord(name)),[left,top]=positions[i],change=animate?(state.newConcepts.has(name)?"change-new":state.grownConcepts.has(name)?"change-grown":""):"",labelPosition=labelPositions[i];return`<button class="fruit stage-${stage} ${change} ${labelPosition}" data-concept="${name}" aria-label="${stage?name:"尚未认识的果子"}" style="left:${left}%;top:${top}%;--change-delay:${i*90}ms"><span>${stage?name:"?"}</span></button>`}).join("");return`<article class="tree-card" style="--leaf:${tree.leaf};--fruit:${tree.fruit}"><h3>${tree.name}</h3><p>${tree.subtitle} · ${lit}/${tree.concepts.length}</p><div class="tree-visual"><div class="trunk"></div><div class="canopy">${fruits}</div></div><div class="tree-progress"><i style="width:${lit/tree.concepts.length*100}%"></i></div></article>`}).join("");document.querySelectorAll(".fruit").forEach(button=>button.addEventListener("click",()=>showConcept(button.dataset.concept)))}
function renderHistory(){const list=progress.history||[];$("history-list").innerHTML=list.length?list.map(item=>{const date=new Date(item.id),name=item.mode==="feeling"?"识别感受":"弦外之音";return`<article><div><b>${name}</b><span>${date.toLocaleDateString("zh-CN")} ${date.toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}</span></div><strong>${item.correct}/${item.total}</strong><p>最长连对 ${item.bestStreak} 题 · 新认识 ${item.newCount} 个概念</p></article>`}).join(""):"<div class=\"history-empty\">完成一局训练后，记录会保存在这台浏览器里。</div>"}
function resetProgress(){track("progress_reset_confirmed",{previousRounds:progress.rounds,previousAttempts:progress.attempts,analyticsKept:true});localStorage.removeItem(STORE_KEY);progress=emptyProgress();analytics.anonymousId=progress.anonymousId;saveAnalytics();$("reset-layer").classList.add("is-hidden");$("concept-drawer").classList.add("is-hidden");renderOrchard();renderHistory();updateHome()}
function showConcept(name){const tree=trees.find(t=>t.concepts.includes(name)),record=conceptRecord(name),stage=masteryStage(record);track("concept_opened",{concept:name,tree:tree.id,stage,seen:record.seen||0,correct:record.correct||0});$("concept-tree-name").textContent=tree.name;$("concept-name").textContent=stage?name:"尚未认识";$("concept-definition").textContent=stage?defs[name]:"在训练中遇见它，正确答案就会揭开这颗果子的名字。";const labels=["未遇见","已经认识，等待第一次答对","正在成长，多换几个情境练习","已经成熟，可以稳定调用"];$("concept-progress").textContent=`成熟阶段：${labels[stage]}${stage?` · 遇见 ${record.seen} 次，答对 ${record.correct} 次`:""}`;$("concept-drawer").classList.remove("is-hidden")}
function openOrchard(){track("orchard_opened",{fromScreen:Object.keys(screens).find(key=>!screens[key].classList.contains("is-hidden"))});clearTimers();renderOrchard();renderHistory();showScreen("orchard");$("settlement-layer").classList.add("is-hidden");$("concept-drawer").classList.add("is-hidden")}
function goHome(){track("home_opened",{fromScreen:Object.keys(screens).find(key=>!screens[key].classList.contains("is-hidden")),roundId:state.roundId,mode:state.mode,index:state.index+1});clearTimers();$("settlement-layer").classList.add("is-hidden");$("concept-drawer").classList.add("is-hidden");updateHome();showScreen("home")}

document.addEventListener("click",e=>{const el=e.target.closest("button,a");if(!el)return;track("ui_click",{id:el.id||null,text:(el.textContent||el.getAttribute("aria-label")||"").trim().slice(0,40),className:el.className||null,mode:el.dataset.mode||null,concept:el.dataset.concept||null})},{capture:true});
if($("image-priority-toggle")){$("image-priority-toggle").checked=localStorage.getItem(IMAGE_PRIORITY_KEY)==="1";$("image-priority-toggle").addEventListener("change",e=>{localStorage.setItem(IMAGE_PRIORITY_KEY,e.currentTarget.checked?"1":"0");track("image_priority_toggle",{enabled:e.currentTarget.checked})})}
if($("creator-mode-toggle")){$("creator-mode-toggle").checked=localStorage.getItem(CREATOR_MODE_KEY)==="1";$("creator-mode-toggle").addEventListener("change",e=>{localStorage.setItem(CREATOR_MODE_KEY,e.currentTarget.checked?"1":"0");track("creator_mode_toggle",{enabled:e.currentTarget.checked})})}
document.querySelectorAll(".mode-start").forEach(b=>b.addEventListener("click",()=>startGame(b.dataset.mode)));
$("open-orchard").addEventListener("click",openOrchard);$("orchard-home").addEventListener("click",goHome);$("quit-game").addEventListener("click",()=>{track("round_quit",{roundId:state.roundId,mode:state.mode,index:state.index+1,correct:state.correct});goHome()});$("submit-answer").addEventListener("click",()=>resolveAnswer($("answer-input").value));$("answer-input").addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();e.stopPropagation();track("answer_enter_pressed",{roundId:state.roundId,mode:state.mode,index:state.index+1});resolveAnswer(e.currentTarget.value)}});document.addEventListener("keydown",e=>{if(e.key==="Enter"&&!$("feedback-layer").classList.contains("is-hidden")){e.preventDefault();track("feedback_enter_pressed",{roundId:state.roundId,index:state.index+1});advance()}});$("next-question").addEventListener("click",advance);$("close-concept").addEventListener("click",()=>{track("concept_closed",{});$("concept-drawer").classList.add("is-hidden")});$("stay-orchard").addEventListener("click",revealOrchardChanges);$("play-again").addEventListener("click",()=>{track("play_again",{previousRoundId:state.roundId,mode:state.mode});startGame(state.mode)});$("clear-progress").addEventListener("click",()=>{track("progress_reset_requested",{rounds:progress.rounds,attempts:progress.attempts});$("reset-layer").classList.remove("is-hidden")});$("cancel-reset").addEventListener("click",()=>{track("progress_reset_cancelled",{});$("reset-layer").classList.add("is-hidden")});$("confirm-reset").addEventListener("click",resetProgress);
track("app_loaded",{title:document.title,referrer:document.referrer||null});
updateHome();
})();
