(function(){
const {trees,defs,feelings,subtexts}=window.GAME_DATA;
const $=id=>document.getElementById(id);
const screens={home:$("home-screen"),game:$("game-screen"),orchard:$("orchard-screen")};
const STORE_KEY="eq-superman-mvp-v1";
const emptyProgress=()=>({rounds:0,attempts:0,concepts:{}});
let progress=loadProgress();
let state={mode:null,deck:[],index:0,seconds:20,timer:null,autoTimer:null,locked:false,correct:0,streak:0,bestStreak:0,sessionConcepts:new Set(),newConcepts:new Set(),grownConcepts:new Set()};

function loadProgress(){try{return {...emptyProgress(),...JSON.parse(localStorage.getItem(STORE_KEY)||"{}")}}catch{return emptyProgress()}}
function saveProgress(){localStorage.setItem(STORE_KEY,JSON.stringify(progress))}
function shuffle(items){return [...items].sort(()=>Math.random()-.5)}
function showScreen(name){Object.entries(screens).forEach(([key,el])=>el.classList.toggle("is-hidden",key!==name));window.scrollTo(0,0)}
function normalize(text){return text.trim().toLowerCase().replace(/[，。！？、,.!?“”"'\s]/g,"").replace(/我觉得|我感到|感觉是|应该是|有一点|有点|非常/g,"")}
function conceptRecord(name){return progress.concepts[name]||{seen:0,correct:0,questionIds:[],modes:[],lastSeen:null}}
function masteryStage(record){if(!record.seen)return 0;if(!record.correct)return 1;if(record.correct<3||record.questionIds.length<2)return 2;return 3}
function allConceptNames(){return trees.flatMap(tree=>tree.concepts)}
function stats(){const records=allConceptNames().map(conceptRecord);return{discovered:records.filter(r=>r.seen).length,ripe:records.filter(r=>masteryStage(r)===3).length,total:records.length}}
function updateHome(){const s=stats();$("home-fruit-count").textContent=s.discovered;$("stat-discovered").textContent=s.discovered;$("stat-ripe").textContent=s.ripe;$("stat-rounds").textContent=progress.rounds}

function startGame(mode){clearTimers();const source=mode==="feeling"?feelings:subtexts;state={mode,deck:shuffle(source).slice(0,8),index:0,seconds:20,timer:null,autoTimer:null,locked:false,correct:0,streak:0,bestStreak:0,sessionConcepts:new Set(),newConcepts:new Set(),grownConcepts:new Set()};const feeling=mode==="feeling";$("game-mode-index").textContent=feeling?"01":"02";$("game-mode-name").textContent=feeling?"识别感受":"弦外之音";$("game-mode-goal").textContent=feeling?"为这一刻找到名字":"听见没有说出口的需要";showScreen("game");renderQuestion()}
function renderQuestion(){const q=state.deck[state.index];state.seconds=20;state.locked=false;$("question-current").textContent=state.index+1;$("question-total").textContent=state.deck.length;$("progress-bar").style.width=`${(state.index+1)/state.deck.length*100}%`;$("context-label").textContent=q.context;$("scene-text").textContent=q.scene;$("question-prompt").textContent=q.prompt;$("npc-status").textContent=state.mode==="feeling"?"想请你听一件事":"这句话好像没有说完";$("answer-label").textContent=state.mode==="feeling"?"用一个感受词回答":"用一个词或一句短话回答";$("answer-input").placeholder=state.mode==="feeling"?"例如：委屈":"例如：希望被重视";$("answer-input").maxlength=state.mode==="feeling"?12:40;$("answer-input").value="";$("answer-input").disabled=false;$("submit-answer").disabled=false;$("answer-hint").textContent=state.mode==="feeling"?"越准确的词，越能接近这一刻。":"不用猜台词，试着说出背后的感受或需要。";updateTimer();clearInterval(state.timer);state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0)resolveAnswer("",true)},1000);setTimeout(()=>$("answer-input").focus(),80)}
function updateTimer(){$("timer").textContent=state.seconds;$("timer").classList.toggle("urgent",state.seconds<=5)}
function grade(q,raw,timedOut){if(timedOut||!normalize(raw))return"timeout";const answer=normalize(raw);if(q.accepted.some(word=>answer.includes(normalize(word))))return"correct";if((q.near||[]).some(word=>answer.includes(normalize(word))))return"near";return"wrong"}
function recordAttempt(q,passed){const before=conceptRecord(q.concept),beforeStage=masteryStage(before);const record={...before,seen:before.seen+1,correct:before.correct+(passed?1:0),questionIds:[...new Set([...before.questionIds,q.id])],modes:[...new Set([...before.modes,q.mode])],lastSeen:new Date().toISOString()};progress.concepts[q.concept]=record;progress.attempts++;saveProgress();const afterStage=masteryStage(record);state.sessionConcepts.add(q.concept);if(beforeStage===0)state.newConcepts.add(q.concept);if(afterStage>beforeStage&&beforeStage>0)state.grownConcepts.add(q.concept)}
function resolveAnswer(raw,timedOut=false){if(state.locked)return;state.locked=true;clearInterval(state.timer);const q=state.deck[state.index],verdict=grade(q,raw,timedOut),passed=verdict==="correct";recordAttempt(q,passed);$("answer-input").disabled=true;$("submit-answer").disabled=true;if(passed){state.correct++;state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak)}else state.streak=0;const card=$("feedback-card");card.classList.toggle("fail",!passed);$("feedback-icon").textContent=passed?"✓":"×";$("feedback-kicker").textContent=passed?"你听准了":verdict==="near"?"很接近，再准一点":verdict==="timeout"?"时间到了":"这一次没有命中";$("feedback-target").textContent=`${passed?"准确答案":"更贴近的是"}：${q.target}`;$("feedback-reference").textContent=state.mode==="subtext"?`参考表达：${q.reference}`:`关键词：${q.target}`;$("feedback-explanation").textContent=q.explanation;$("feedback-score").textContent=passed?`+1 果实经验 · ${state.streak} 连续答对`:`「${q.concept}」已收进果园，等待下次长大`;$("next-question").textContent=state.index===state.deck.length-1?"查看果园 →":"下一题 →";$("feedback-layer").classList.remove("is-hidden");clearTimeout(state.autoTimer);state.autoTimer=setTimeout(advance,3600)}
function advance(){if($("feedback-layer").classList.contains("is-hidden"))return;clearTimeout(state.autoTimer);$("feedback-layer").classList.add("is-hidden");state.index++;if(state.index>=state.deck.length)finishRound();else renderQuestion()}
function finishRound(){clearTimers();progress.rounds++;saveProgress();renderOrchard();showScreen("orchard");$("settle-correct").textContent=`${state.correct}/${state.deck.length}`;$("settle-new").textContent=state.newConcepts.size;$("settle-grown").textContent=state.grownConcepts.size;$("settlement-title").textContent=state.correct>=6?"这一局，你听得很准":"果园记住了这次练习";$("settlement-copy").textContent=`完成「${state.mode==="feeling"?"识别感受":"弦外之音"}」，最长连续答对 ${state.bestStreak} 题。`;const names=[...new Set([...state.newConcepts,...state.grownConcepts])];$("settle-fruits").innerHTML=names.length?names.map(n=>{const label=state.newConcepts.has(n)&&state.grownConcepts.has(n)?"新认识并长大":state.newConcepts.has(n)?"新认识":"长大";return`<span>${label} · ${n}</span>`}).join(""):"<span>继续练习，果子会慢慢成熟</span>";$("settlement-layer").classList.remove("is-hidden");updateHome()}
function clearTimers(){clearInterval(state.timer);clearTimeout(state.autoTimer)}

const positions=[[28,25],[60,18],[48,46],[20,57],[70,58],[38,73],[60,80],[78,36]];
function renderOrchard(){const s=stats();$("orchard-summary").textContent=`${s.discovered} / ${s.total} 已点亮`;$("orchard-map").innerHTML=trees.map(tree=>{const lit=tree.concepts.filter(name=>conceptRecord(name).seen).length;const fruits=tree.concepts.map((name,i)=>{const stage=masteryStage(conceptRecord(name)),[left,top]=positions[i];return`<button class="fruit stage-${stage}" data-concept="${name}" aria-label="${stage?name:"尚未认识的果子"}" style="left:${left}%;top:${top}%"><span>${stage?name:"?"}</span></button>`}).join("");return`<article class="tree-card" style="--leaf:${tree.leaf};--fruit:${tree.fruit}"><h3>${tree.name}</h3><p>${tree.subtitle} · ${lit}/${tree.concepts.length}</p><div class="tree-visual"><div class="trunk"></div><div class="canopy">${fruits}</div></div><div class="tree-progress"><i style="width:${lit/tree.concepts.length*100}%"></i></div></article>`}).join("");document.querySelectorAll(".fruit").forEach(button=>button.addEventListener("click",()=>showConcept(button.dataset.concept)))}
function showConcept(name){const tree=trees.find(t=>t.concepts.includes(name)),record=conceptRecord(name),stage=masteryStage(record);$("concept-tree-name").textContent=tree.name;$("concept-name").textContent=stage?name:"尚未认识";$("concept-definition").textContent=stage?defs[name]:"在训练中遇见它，正确答案就会揭开这颗果子的名字。";const labels=["未遇见","已经认识，等待第一次答对","正在成长，多换几个情境练习","已经成熟，可以稳定调用"];$("concept-progress").textContent=`成熟阶段：${labels[stage]}${stage?` · 遇见 ${record.seen} 次，答对 ${record.correct} 次`:""}`;$("concept-drawer").classList.remove("is-hidden")}
function openOrchard(){clearTimers();renderOrchard();showScreen("orchard");$("settlement-layer").classList.add("is-hidden");$("concept-drawer").classList.add("is-hidden")}
function goHome(){clearTimers();$("settlement-layer").classList.add("is-hidden");$("concept-drawer").classList.add("is-hidden");updateHome();showScreen("home")}

document.querySelectorAll(".mode-start").forEach(b=>b.addEventListener("click",()=>startGame(b.dataset.mode)));
$("open-orchard").addEventListener("click",openOrchard);$("orchard-home").addEventListener("click",goHome);$("quit-game").addEventListener("click",goHome);$("submit-answer").addEventListener("click",()=>resolveAnswer($("answer-input").value));$("answer-input").addEventListener("keydown",e=>{if(e.key==="Enter")resolveAnswer(e.currentTarget.value)});$("next-question").addEventListener("click",advance);$("close-concept").addEventListener("click",()=>$("concept-drawer").classList.add("is-hidden"));$("stay-orchard").addEventListener("click",()=>$("settlement-layer").classList.add("is-hidden"));$("play-again").addEventListener("click",()=>startGame(state.mode));
updateHome();
})();
